# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.supportedFilesystems = [ "btrfs" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXVOL";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:1" "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIXVOL";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:1" "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIXVOL";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:1" "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }];

  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
